package persistence.entity.metadata;

import jakarta.persistence.GenerationType;
import persistence.inspector.EntityFieldInspector;
import persistence.sql.DataType;

import java.lang.reflect.Field;

public class EntityColumn {
    private String tableName;
    private Field field;
    private String fieldName;
    private String columnName;
    private int sqlTypeCode;
    private boolean isPrimaryKey;
    private boolean isNullable;
    private GenerationType generationType;
    private int length;

    public EntityColumn() {
    }

    public EntityColumn(String tableName, Field field, String fieldName, String columnName, int sqlTypeCode, boolean isPrimaryKey, boolean isNullable, GenerationType generationType, int length) {
        this.tableName = tableName;
        this.field = field;
        this.fieldName = fieldName;
        this.columnName = columnName;
        this.sqlTypeCode = sqlTypeCode;
        this.isPrimaryKey = isPrimaryKey;
        this.isNullable = isNullable;
        this.generationType = generationType;
        this.length = length;
    }

    public static EntityColumn fromField(String tableName, Field field, DataType dataType) {
        return new EntityColumn(
                tableName,
                field,
                EntityFieldInspector.getFieldName(field),
                EntityFieldInspector.getColumnName(field),
                dataType.getSqlTypeCode(field.getType()),
                EntityFieldInspector.isPrimaryKey(field),
                EntityFieldInspector.isNullable(field),
                EntityFieldInspector.getGenerationType(field),
                EntityFieldInspector.getLength(field)
        );
    }


    public String getTableName() {
        return tableName;
    }

    public Field getField() {
        return field;
    }

    public void setField(Field field) {
        this.field = field;
    }

    public String getFieldName() {
        return fieldName;
    }

    public boolean isDataAutoGenerated() {
        return isPrimaryKey && generationType != null;
    }

    public String getColumnName() {
        return columnName;
    }

    public int getSqlTypeCode() {
        return sqlTypeCode;
    }

    public boolean isPrimaryKey() {
        return isPrimaryKey;
    }

    public boolean isNullable() {
        return isNullable;
    }

    public GenerationType getGenerationType() {
        return generationType;
    }

    public int getLength() {
        return length;
    }

    @Override
    public String toString() {
        return "EntityColumn{" +
            "name='" + columnName + '\'' +
            ", sqlTypeCode=" + sqlTypeCode +
            ", isPrimaryKey=" + isPrimaryKey +
            ", isNullable=" + isNullable +
            ", generationType=" + generationType +
            ", length=" + length +
            '}';
    }

    public Object getValue(Object entity) {
        field.setAccessible(true);
        try {
            return field.get(entity);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

    public void setValue(Object object, Object value) {
        field.setAccessible(true);
        try {
            field.set(object, value);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

}
